# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: terrarium

env:
  - DOCKER_REGISTRY=ghcr.io/macropower

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: terrarium
    main: ./cmd/terrarium
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.jacobcolvin.com/x/version.Version={{.Version}}
      - -X go.jacobcolvin.com/x/version.Branch={{.Branch}}
      - -X go.jacobcolvin.com/x/version.BuildUser={{.Env.USER}}@{{.Env.HOSTNAME}}
      - -X go.jacobcolvin.com/x/version.BuildDate={{.Date}}
    flags:
      - -trimpath
    buildmode: pie

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nix:
  - name: terrarium
    repository:
      owner: MacroPower
      name: nur-packages
    url_template: >-
      https://github.com/macropower/terrarium/releases/download/{{ .Tag }}/
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
      .tar.gz
    commit_msg_template: "chore: pkg update for {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: botty-mcbottington
      email: 168950816+botty-mcbottington[bot]@users.noreply.github.com
    homepage: "https://github.com/macropower/terrarium"
    description: "Secure container environment using Envoy as an L7 egress gateway"
    license: "asl20"
    skip_upload: auto
    dependencies:
      - envoy-bin
      - util-linux
